# rosbag folder
rosbag_input_folder: /mnt/data_2/Rosbag/ljp/1209

# rosbag path
rosbag_input_path_list: [
  
  ]

# rosbag path
rosbag_output_path: /mnt/data_2/Rosbag/qunguang1_2_2021-12-09-11-01-17_0.bag

# progress debug
debug: False
