# rosbag folder
rosbag_input_folder: /mnt/data_2/Rosbag/parking/wudazhuoer_parking/zhuoer_20211018

# rosbag path
rosbag_input_path_list: [

]

# rosbag path
rosbag_output_path: /mnt/data_2/Rosbag/wudazhuoerdiku_2021-10-18-19-56-43_0

# progress debug
debug: False
