# rosbag folder
rosbag_input_folder:

# rosbag path
rosbag_input_path_list: ["/mnt/data_2/Rosbag/ljp/1108/chu1_2021-11-08-10-56-15_0.bag",
                         "/mnt/data_2/Rosbag/ljp/1108/chu1_2021-11-08-10-56-15_1.bag",
                         "/mnt/data_2/Rosbag/ljp/1108/chu1_2021-11-08-10-56-15_2.bag"]

# rosbag path
rosbag_output_path: /mnt/data_2/Rosbag/test.bag

# progress debug
debug: False
