# rosbag folder
rosbag_input_folder: /home/leidi/Desktop/lantu_6cam_val_20220801/cam_0801/lantu_6cam

# rosbag path
rosbag_input_path_list: []

# rosbag path
rosbag_output_path: /home/leidi/Desktop/lantu_6cam_val_20220801/cam_0801/lantu_6cam_val_20220801.bag

# progress debug
debug: False
