# rosbag folder
rosbag_input_folder: /mnt/data_2/Rosbag/ljp/1015

# rosbag path
rosbag_input_path_list: []

# rosbag path
rosbag_output_path: /mnt/data_2/Rosbag/parking/guoruan_2021-10-15-15-15-13_0.bag

# progress debug
debug: False
